In [9]:
import pandas as pd
import numpy as np
from tqdm import tqdm
df_list = []
for i in tqdm(range(1, 50)):
    if i == 6:
        continue
    str = f'./data_double_nucleotides/train_{i}_0.xlsx'
    df1 = pd.read_excel(str)
    new_columns = np.arange(76)
    df1.columns = new_columns
    df1.insert(df1.shape[1], 76, 0)
    new_df = [df1]*20
    all_df = pd.concat(new_df, axis=0)
    df_list.append(all_df)

  0%|                                                                                           | 0/49 [00:03<?, ?it/s]

KeyboardInterrupt:

In [8]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from multiprocessing.dummy import Pool as ThreadPool
import threadpool

In [28]:
data_list = np.arange(1,50)

In [29]:
data_list = data_list.tolist()

In [30]:
data_list.remove(6)

In [31]:
len(data_list)

48

In [32]:
num_tasks = len(data_list)
sub_tasks = [(data) for data in data_list]

In [33]:
sub_tasks
df_list = []

In [ ]:
pool_t = threadpool.ThreadPool(4)
requestss = threadpool.makeRequests(data_pro, sub_tasks)
[pool_t.putRequest(req) for req in requestss]
pool_t.wait()

train_1_0.xlsx finished
train_4_0.xlsx finished
train_2_0.xlsx finished
train_3_0.xlsx finished

In [25]:
import time
import threadpool
time1 = int(time.time())
str = f'./data_double_nucleotides/train_1_0.xlsx'
df1 = pd.read_excel(str)
new_columns = np.arange(76)
df1.columns = new_columns
df1.insert(df1.shape[1], 76, 0)
new_df = [df1]*20
all_df = pd.concat(new_df, axis=0)
df_list.append(all_df)
print(f"train_1_0.xlsx finished")
time2 = int(time.time())
time2 = time2 - time1
print(time2)
pool_t = threadpool.ThreadPool(4)
time1 = int(time.time())
requestss = threadpool.makeRequests(data_pro, sub_tasks)
[pool_t.putRequest(req) for req in requestss]
pool_t.wait()
time2 = int(time.time())
time2 = time2 - time1

train_1_0.xlsx finished
51
train_4_0.xlsx finished
train_2_0.xlsx finished
train_3_0.xlsx finished
train_1_0.xlsx finished

In [26]:
print(time2)

225

In [34]:
import concurrent.futures
 
 
def data_pro(i):
    str = f'./data_double_nucleotides/train_{i}_0.xlsx'
    df1 = pd.read_excel(str)
    new_columns = np.arange(76)
    df1.columns = new_columns
    df1.insert(df1.shape[1], 76, 0)
    new_df = [df1]*20
    all_df = pd.concat(new_df, axis=0)
    df_list.append(all_df)
    print(f"train_{i}_0.xlsx finished")
with concurrent.futures.ProcessPoolExecutor() as executor:
        executor.map(data_pro, sub_tasks)

BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

In [6]:
def data_pro(i):
    str = f'./data_double_nucleotides/train_{i}_0.xlsx'
    df1 = pd.read_excel(str)
    new_columns = np.arange(76)
    df1.columns = new_columns
    df1.insert(df1.shape[1], 76, 0)
    new_df = [df1]*20
    all_df = pd.concat(new_df, axis=0)
    df_list.append(all_df)
    print(f"train_{i}_0.xlsx finished")

In [ ]:
pool = ThreadPool()
results = pool.map(data_pro, item_list)
pool.close()
pool.join()

In [4]:
ThreadPool??

Signature: ThreadPool(processes=None, initializer=None, initargs=())
Docstring: <no docstring>
Source:
def Pool(processes=None, initializer=None, initargs=()):
    from ..pool import ThreadPool
    return ThreadPool(processes, initializer, initargs)
File:      c:\users\jiang su\.conda\envs\pytorch\lib\multiprocessing\dummy\__init__.py
Type:      function

In [ ]:
import multiprocessing
import time
def data_pro(i):
    str = f'./data_double_nucleotides/train_{i}_0.xlsx'
    df1 = pd.read_excel(str)
    new_columns = np.arange(76)
    df1.columns = new_columns
    df1.insert(df1.shape[1], 76, 0)
    new_df = [df1]*20
    all_df = pd.concat(new_df, axis=0)
    df_list.append(all_df)
    print(f"train_{i}_0.xlsx finished")
pool = multiprocessing.Pool(processes = 3)
pool.apply_async(data_pro, sub_tasks)
pool.close()
pool.join()

In [ ]:
from multiprocessing.dummy import Pool as ThreadPool
pool = ThreadPool()
results = pool.map(process, item_list)
pool.close()
pool.join()

In [2]:
df_list

[       0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0      12  14   1   8  11   1   4  11   4  10  ...  13   3  13   8   6  16
 1       7   9   3   1  11   1   9   4   5   9  ...   4   9   7   6  16  14
 2      11   1   9   3   9   1   5  10  15   2  ...   9  11  16   8  14   9
 3       6   1   5   2   5   3   1  13   8   6  ...   4   5   2  11   1  12
 4      13   9   3  13   1  13   1  16   3  15  ...  10   9   2  11  16   5
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30947   7  10   8   6  11  14   2   5   9  10  ...  13   5   1   7   9   6
 30948  13   6   2   2  10  12  14   3  14   5  ...   2  12   9  13  11   2
 30949   3  11   3  15   7  16  15  14  11   1  ...  10   3   9   8   1   9
 30950   3  15   7  16  15   3   5   3  10   9  ...   7  12   9   7  10   4
 30951   9   3  14  11   2  10   5   3  12  16  ...   4   2  15   3   8   5

        73  74  75  76
 0       8   2  11   0
 1       9  16  10   0
 2      13  15   4   0
 3      15   3  11   0
 4      10  11   8   0
 ...    ..  ..  ..  ..
 30947  14  10   1   0
 30948   3  13   6   0
 30949   6  15   3   0
 30950   9   9   1   0
 30951   3   6  14   0

 [619040 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       3  11   1  11   1  13  11   1   2  16  ...   1  16   3  14  14   6
 1      16  13   3  10   6   1  10   6  12  14  ...   5  16  12   3   8   3
 2      16  12   9   2   2   2   6   4   5   6  ...  15   1   9   9  14   6
 3       9   2   2   2  14  10  10   8  15  12  ...  13   9   3   4  14  13
 4       1  15   6   3   5   5  12  15  13   2  ...   8  12  16  11   8  14
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30536   4  11  12  10   8  13  12   8   3  11  ...   8   8   8  13   3   4
 30537  15  12   5  15   5   1   7  10   6  15  ...  13   6  15  14   7  16
 30538   4  10   1   4   2  14   6  10   2  13  ...   3  16   5  11  10   4
 30539  15   9  15   5   3  12   4  12  15   1  ...  10  11  14   2   2  12
 30540  10   8  15  15   8  10   1   8   3   7  ...   1   4   4  11   3   5

        73  74  75  76
 0      11  16   4   0
 1       8   3  12   0
 2       3  14   5   0
 3       9   3   5   0
 4       1   2  10   0
 ...    ..  ..  ..  ..
 30536  12   4  10   0
 30537   1  13  13   0
 30538   9  10  14   0
 30539  13  16   4   0
 30540   4   3   6   0

 [610820 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       6   1   6   3   5   8   5   6  12  11  ...   7   3   8   3   5  14
 1       9   2   2   2  14  10  10   8  15   7  ...  13  10   4   5   5   6
 2      10  16   9  15   5  16   4  15  14  14  ...  11  13   4  13  13   2
 3      15   4  10   4  13   9  12  12   2   4  ...  10  14   9   8   6   7
 4       9   3   1  11   1   2  15  15   5   4  ...   6   5  13  14   8   2
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30987   3  12   7   8  12   4  10   5   5  14  ...   9   9  10   9   5  11
 30988   7   7   5   6   9  16   4   7   8   7  ...   7  11  14   8  15  13
 30989   2   7   4  15   9  11  12  14   3   6  ...  11   1   2  16   3   8
 30990   9  16  11   3  11   5   2   2   4   6  ...   6  10  12   7   7  11
 30991  10   6   4   2   5  14  13   1  12  10  ...   5  16   8  11   3  16

        73  74  75  76
 0       9  15   7   0
 1      14  10   4   0
 2       8   8   9   0
 3      12   9   7   0
 4       2   6   4   0
 ...    ..  ..  ..  ..
 30987   5   7   6   0
 30988   4   6   5   0
 30989   6  13   6   0
 30990   1  16  14   0
 30991   7   5  13   0

 [619840 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       3  11   1  11   1  13  11   1   4  10  ...   9   9  11   6   5   6
 1       2   2  14  10  11   8  13   6  15   2  ...  14  15   8   2  14  14
 2       3  12   4   2  15  14   7  11   7   9  ...   4   8  14  12  10  15
 3      10  16   9  15   5  16   4  15  12   9  ...  15  12  12   5   4   1
 4       9   3   9   1   8   8   3   1  15   9  ...   5  13  14  10   7   2
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30935  11   9  12  10  12  16  12   5  13   5  ...   4   9   7   1   8  16
 30936   3   5  12  16   5  10   4  11   3   4  ...  15  12  14   2  16   9
 30937   3   5  16  15  10  10   5  10   3  15  ...  16  13  13   5  16   3
 30938   5  16  15  10  10   5   6  11  14   5  ...  12   4   6   3  15   2
 30939  14   2   3   7   6  16  11   2  13   3  ...   8  11  13   4  12  15

        73  74  75  76
 0       8   5  11   0
 1      15  16   5   0
 2      12  11  16   0
 3       4   4   4   0
 4      12  12   1   0
 ...    ..  ..  ..  ..
 30935   9   3  10   0
 30936   6   7  12   0
 30937  12  16  12   0
 30938   9   2  15   0
 30939  13  16  12   0

 [618800 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       1  11  10   5  12  15   3   1  14   3  ...   9   3   6  13  12   4
 1      13  13   8  12   6  10   7   3  11   4  ...  15  10   1   7   9   1
 2      13   9   2   7  16  12   6  16   7  11  ...   7  16  10   1  14   6
 3       5  10   2   3  14   2  10  14   7   8  ...   7  12   9   1   8   4
 4       5   5  12   5   5   4  14  11   8  16  ...   1  15   1   4  15   8
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30620   3   1  13  15  12   5  13   8  15   4  ...   2   8   4   6  15  12
 30621  14   4   3  13   3   5   2   3   7   4  ...  13   1  15   9  15   6
 30622   3   5  14   1  13   4  11   4   9   9  ...  15   8  11  10   5   1
 30623  10   3   6  13   7   7   8   1   4  13  ...  13  10  10   6   4   8
 30624   2   8   9  14   5   6   8  16   1   9  ...  16   4  13   2   7   8

        73  74  75  76
 0      10   8   6   0
 1       5  13   2   0
 2      10   3  11   0
 3      16   1  16   0
 4       3   5  15   0
 ...    ..  ..  ..  ..
 30620   2  16   9   0
 30621  14  16   7   0
 30622   9  16  11   0
 30623   2  11   7   0
 30624  16   2  12   0

 [612500 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0      13  11  16   5   2  15   3   1  15   3  ...  16  13  12   4  10  12
 1       5   8  16   1  11   6  14  11  16   5  ...  10   3   1  10   8  10
 2       1   2   8   9   4  14   5   5  16  11  ...  11   5  16   1  13   5
 3      15   1   5   5   8   7  13   7   6  14  ...  15  14   4  10  13   6
 4       6   3   3   3  12   4  11  12   6  16  ...  13  12  12  15   9  13
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30814   3   9   9   8   7  14   7  10   4  15  ...  11  10   5   1  12   2
 30815  13  16   9  13   8   7  12   3  16  11  ...   4   5  16   4   7   8
 30816  14   7   7  12   2   9   7  15  14   8  ...  14   7   5   5   4  10
 30817  11  13   7   4   9   4   8  14  16   6  ...  10  12   4   4  10  11
 30818   3  13   4   2   3  15  12   2   2  14  ...  13   8   1  10   5  11

        73  74  75  76
 0       8  11   4   0
 1       5  16   6   0
 2      11  15  13   0
 3       5  16   6   0
 4       3   4   9   0
 ...    ..  ..  ..  ..
 30814  12  10  16   0
 30815   9   7   3   0
 30816   1   8  16   0
 30817   5  14  15   0
 30818   1  10   3   0

 [616380 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       2  15   9   1  11   1   3   5  13  11  ...   1   7   3  11   3   4
 1       6   3  16   9   9  16   5   3   8  12  ...  13  15  16   7   1  11
 2       3  12   4   2  15  14   7  11   2   6  ...   5   3  11  13   3   5
 3       7   7  10  16   9  15  14  12  15   9  ...  14  16   5  12   3   2
 4      15  14   7   8   3  14  12   6   5   9  ...  12  10  13   8  10   4
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30667   4   4   7   7  15   9   9   2   8   9  ...  12   9   8  16   5  16
 30668   7   7  15   9  11  12   8  16   2  12  ...   9  12   7   2  10   7
 30669   4   4   6   5   6  16   8   8  13  14  ...   4   1   4   8   4   8
 30670  12  11   3  11  16  11  16  14  13  16  ...   4  13  15  10   3  12
 30671   2   8  14   8   8   1  13   2   7  11  ...   9  12   2  11  12   6

        73  74  75  76
 0      14   5   9   0
 1      15   2  13   0
 2      13   6  13   0
 3       6  16   8   0
 4       7  12  12   0
 ...    ..  ..  ..  ..
 30667  14   5  15   0
 30668   4   8  16   0
 30669   5  15   8   0
 30670   2   8  10   0
 30671  10  14  11   0

 [613440 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0      16  14  14   5   9   9   3  16  14   5  ...  13  10   5  16   1  13
 1      16   8   6   3   3   3   4   4   9   3  ...  14   9   6  13   5   6
 2       9  15   5  16   3   1   7   4   2  10  ...  14  10  12   1  10   8
 3       3  14   2   3   9  16   8  12   9   1  ...   1  12  15  11   2  13
 4       9   3   9   1   8   8   3   1   5   3  ...   1   2   7  15  12   9
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30891  16   7   3  14  11   2  15  15  16  13  ...  11   5   1  13   6   9
 30892   4  13   6  11   4   7   8   6   4  13  ...   3  14   6  11  12   4
 30893   1  13   8   6  13   3   8   5   8   4  ...   6  12  10  11  16   9
 30894  10   1  11  15   6  16  11  16   4   9  ...   9   4   5   5  14  15
 30895   8   8  10  13   9   8  13   8   2  11  ...   7   5   8  10   5   5

        73  74  75  76
 0      10   2  16   0
 1      10  11  16   0
 2       9  12   7   0
 3       6  13   2   0
 4       6  15   8   0
 ...    ..  ..  ..  ..
 30891   8  16   5   0
 30892   6   5   9   0
 30893  11   5  10   0
 30894  15   7   3   0
 30895   6  13  11   0

 [617920 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       3   5   8  16   1  11   6   2  11   8  ...   9  15  16   9  13  10
 1       1   2   8   9   4  14   5   5  11   9  ...   6   9   6   1   2  12
 2      11   6   3  16   9   9  13  11   5   7  ...   8  14  10  15  12   5
 3       9   2   2   2  14  10  10   8  12  11  ...  10   5   3   9   2   6
 4      13   8  12   6  10  13   2  13   8   2  ...   1  11  16  13   9   7
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30954   3   3  13  13  16   4   9  14  11   1  ...   1   4   7   5   6   5
 30955   1  14  14   7   4  14  10  12  12   9  ...   9   7  15   5   2   3
 30956  10  14  14  16   4  13   2   7   5   5  ...  15   4  10   7  15   4
 30957   5   4   2   1  11   7   5   1  12  13  ...  15   4  14   8  13   7
 30958   1  11   7  14   4  15  12   6   4   2  ...   7  12  16   7   4   6

        73  74  75  76
 0       8   5   9   0
 1      16   6  11   0
 2       2   5   1   0
 3      10   1   6   0
 4      16   7  15   0
 ...    ..  ..  ..  ..
 30954  11   8  10   0
 30955   3  10   5   0
 30956   6   7   3   0
 30957  15   1   9   0
 30958   7   3   1   0

 [619180 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0      11   1  11   1  13  11  13  11   3   2  ...  14   2   9   7   9   9
 1       1   6   3   5   8  16   1   2   4   8  ...  15   7   6   1  16  10
 2       2  15   9   1  11   1   3   5   7  14  ...   3   5   6   9   5   7
 3       3  11   6   3  16   9   9   1   5   4  ...  15   8  13  14   4   3
 4      14   7   8   3  14   2  11   7   2  11  ...   3  13   4   4   6   1
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30727  10   1   7   3  10   9   2   6  13   7  ...   4   2   6  13  15   9
 30728   1   9   5   8   2   1   3  16  11   4  ...  12   7  11   6  14   5
 30729   3   2   2  13   5   1  12  13   1  12  ...  11   7  13  10   1   4
 30730  14   6  11   2   9  15  13   4   3  13  ...  12   6  14  12   7   8
 30731  15   9   6   9   7   8   9   4   5  15  ...  12  10  15   6   8   6

        73  74  75  76
 0       5   8   1   0
 1       6  12  15   0
 2       4   5   1   0
 3      15   1   4   0
 4       9   9   5   0
 ...    ..  ..  ..  ..
 30727   9   4   5   0
 30728   1  14   9   0
 30729  12  15   8   0
 30730   8  15   4   0
 30731  14  10  14   0

 [614640 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       4   3  12  14   1   8   9   9  11  14  ...   1   7  15   9   3  13
 1       2  15   9   1  11   1   3   5  10   2  ...   9  12  16   7  13   3
 2       3  11   6   3  16   9   9   1  12  12  ...  14   1   8  10   5  15
 3      11   6   3  16   9   9  13  11   2  11  ...  10  16   6  12   3  12
 4      16   8   6   3   3   3   4   4  15   6  ...  11   3  11  15   5   9
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30996  11   2   6  16   6  10  10   7   6   4  ...   4   5  12   4   1  15
 30997   1   6  14   1   2   2  11  15  11  14  ...  15   1  16  10  14   9
 30998   8  13   5   5  12  16   6   9  11   7  ...   9   4   7   1   7   6
 30999  13   6   2   2  10  12  14   3   3  11  ...  13  15   3   8  15   5
 31000  12   8   1   3  13  14   6   3  10  15  ...  14   1  14   1   5  10

        73  74  75  76
 0       8  16   6   0
 1       8   6   2   0
 2      11   8   8   0
 3       1  14   1   0
 4       3   2   3   0
 ...    ..  ..  ..  ..
 30996   2   7   6   0
 30997   1   8  11   0
 30998   4  11  12   0
 30999   8  12   5   0
 31000  12  14  12   0

 [620020 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       2  15   9   1  11   1   3   5  13   3  ...  11   2   5  10   8  10
 1       3  12   4   2  15  14   7  11  15   6  ...  12  16   7  16   5   8
 2       7   7  10  16   9  15  14  12   7  13  ...   9   1   6   1   6  11
 3       9   1   8   8   2   3   5  11   6  11  ...   2   4  13   1  14   7
 4      10  15   1  13   9   4  14   5  12  12  ...  10   2   3   4  13   3
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30656  13  15   7  11   3   8  14  16   4  13  ...  11   2   1  14   9   7
 30657   3   9   5  16   9  10   1   5  15   9  ...   8   6   5   9   3   6
 30658  14  10  10   6  12   4  14  15  11   8  ...  16  13  14  15  13   9
 30659   9  14  12   9   7   6   4   7  16   4  ...  12   3   2   6   1  11
 30660   4   6   9  15   1  10  12   8   9   6  ...  12   8  15   1   7   2

        73  74  75  76
 0      14   8   5   0
 1      13   8  16   0
 2      14   8  11   0
 3      10  15  10   0
 4       3   9   3   0
 ...    ..  ..  ..  ..
 30656  10  16  15   0
 30657  16   1  16   0
 30658   9   9   7   0
 30659   6   5   2   0
 30660   1   3   5   0

 [613220 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       3   9   4   3  12  14   1   9  15   5  ...   6  10   7   2   7  10
 1       9   2   2   2  14  10  10   8  16   1  ...  15   2  13  11  12  10
 2      12   6  10  13  12   5   6  12   1   2  ...   7  14  15   5  13   4
 3      16   9  15   5  16   3   9  14   8   1  ...   9  11   7   6  10   9
 4       1  11   1   2  14  13   5  11   6  14  ...  11   8  16   6   2   1
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30870  16   5   3   8   9  10   5   5  11   2  ...   9  11  16   3  13  10
 30871   9  13   3   2   2  13   8   9   2  11  ...   8  14   4  13   7   1
 30872   2   1   3  13  12   3  14  12   8  14  ...   8   8   6   1  15   8
 30873  16  15  11  15   8  16   2   4  11  15  ...   9   9  16   8   2  16
 30874   8  16  10   3  16   3  14   7   2  11  ...  15   5   9   4  15  13

        73  74  75  76
 0       2   9   5   0
 1      14  16  15   0
 2      12   3  16   0
 3      15  10   1   0
 4      15  15  10   0
 ...    ..  ..  ..  ..
 30870  13  11   2   0
 30871  12  10   5   0
 30872  10  16   3   0
 30873  12   3  10   0
 30874  15  15   7   0

 [617500 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       1   2   6   1   6   3   5   6   7   4  ...   9  13   1  11  16   4
 1       9   4   3  12  14   1   5  11  12   8  ...   9  13   6  12  11  15
 2       2  16  13   3  10   6   3  14   8  13  ...  12  11  14   1  16  14
 3       9   2   2   2  14  10  10   8   4  15  ...  15   8  11   5  14  16
 4      15   7   1  15   6   3  15   3  14  12  ...   7   6   3   7  13  10
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30680   9  16  12   5   9   5   7   1  15   3  ...   4   2  12   9  11   3
 30681  12   5   9   5   6  11   4   4   5  11  ...  13  14   4  13   7  13
 30682   2   5   5  11  12   5   7   3  14   5  ...  13  12  13   1  10  15
 30683  11   4   7  14  12  15   6   7   2   3  ...  13  12   1  10  16   8
 30684   6  12   4  13  16   8  11   2  14  12  ...   4  11   7   5  10   6

        73  74  75  76
 0       1   3  12   0
 1      14   9   1   0
 2       7   3  13   0
 3      12  10  10   0
 4       5  13  13   0
 ...    ..  ..  ..  ..
 30680  10  15   3   0
 30681  13   8   3   0
 30682  12   2  11   0
 30683   7   9   7   0
 30684   2   5   2   0

 [613700 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       3   9   4   3  12  14   1   9  15  11  ...  14   5  16   2  16  10
 1       2   2   2  14  10  11   6   9  12  11  ...  16  12   3   8  16  11
 2       2  14  10  11   8  15   2   6  16   4  ...   4   1  12   7  15  12
 3       4  13   9   2   7  16  10  14   1  15  ...  11   3  10  13  13  16
 4       3   9   1   8   8   2   3   9   7  16  ...   8   1   7  16   8  14
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 30547   7   7  15   9  11  12   8  16   1   3  ...   8   8   5   5   7  14
 30548  12  11   3  11  16  11  16  14   6  14  ...  12  13   9  16   9   8
 30549  10  14   2  11   9   3   8  11  12  14  ...  10   8  15   5   4  13
 30550   3   4  11   1   4   8  12  14   3  13  ...   8  11  15   3   6   1
 30551  10  14  10   9   9   1  11   8   6   3  ...  10   4   8  15  12   9

        73  74  75  76
 0       1  16   4   0
 1       5   2   9   0
 2      13   2   6   0
 3      10   4  16   0
 4      12  14  10   0
 ...    ..  ..  ..  ..
 30547   2   8  14   0
 30548   5  13   9   0
 30549  12  10  12   0
 30550  12  12   5   0
 30551   9  13  11   0

 [611040 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0       2  15   9   1  11   1   3   5   3   8  ...   7   5   7  14  13   2
 1       3  12   4   2  15  14   7  11  16  10  ...   4   5   6   5  12  15
 2      11  13  13   8  12   6  11   9  12   4  ...   4   6   5  10  10  13
 3      16   2   5   2   1   6   9   4  11   2  ...   5  11  13  12  14   5
 4       2   1   6   1  11  15   5   5  13  14  ...  14   7  16  14  15  15
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..
 29572  10   7   7  14   3  11  15   7   2   7  ...   9  15   9  16  10   8
 29573  13  16   1   6  16   8  10   9  16   3  ...   3   4   2   7   5  14
 29574  11  12  15   7   7  15   7   5   7   1  ...  13   1  10   6  10  12
 29575   2   4   7   7  14  10   7  13   6   5  ...   1   8   9   7  14  14
 29576   7  15  10  14  14  16  11  12   9   4  ...  15  13   1   5  11   7

        73  74  75  76
 0      15  16   3   0
 1      11   7   3   0
 2       6   7  16   0
 3       1  13   6   0
 4       2  14   1   0
 ...    ..  ..  ..  ..
 29572   6   8  15   0
 29573   6  10   5   0
 29574   2   4   4   0
 29575   6   9  11   0
 29576  16  10   2   0

 [591540 rows x 77 columns],
        0   1   2   3   4   5   6   7   8   9   ...  67  68  69  70  71  72  \
 0      11   1  11   1  13  11  13  11   6  11  ...  12  16   1  16   9   5
 1       1  11   1  13  11  16   5   3   6  10  ...  11   4   9  11  16  13
 2       2   5  10   2  16  13   1   5   7   1  ...   1  16  12  15   5   5
 3      13   3  10   6   1   2  15   4   9   3  ...   8   2   5  16   9   6

In [11]:
a = df_list[:8]

In [ ]:

for i in range(1, 6):
    b = df_list[i*8: i*8+8]
    df_temp = pd.concat(b, axis=0)
    pd.to_pickle(df_temp, f'df_double_neg_{i*8}_{i*8+8}.pkl')

In [17]:
print(f'df_double_neg_{1*8}_{1*8+8}.pkl')

df_double_neg_8_16.pkl

In [2]:
import multiprocessing

In [3]:
def data_process(i):
    b = df_list[i*8: i*8+8]
    df_temp = pd.concat(b, axis=0)
    pd.to_pickle(df_temp, f'df_double_neg_{i*8}_{i*8+8}.pkl')

In [4]:
data = [1, 2, 3, 4, 5]