In [1]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd

In [5]:
df_data1_0 = pd.read_excel('./data/train_1_0.xlsx')
df_data1_1 = pd.read_excel('./data/train_1_1.xlsx')
df_data2_0 = pd.read_excel('./data/train_2_0.xlsx')
df_data2_1 = pd.read_excel('./data/train_2_1.xlsx')
df_data3_0 = pd.read_excel('./data/train_3_0.xlsx')
df_data3_1 = pd.read_excel('./data/train_3_1.xlsx')
df_data4_0 = pd.read_excel('./data/train_4_0.xlsx')
df_data4_1 = pd.read_excel('./data/train_4_1.xlsx')
df_data5_0 = pd.read_excel('./data/train_5_0.xlsx')
df_data5_1 = pd.read_excel('./data/train_5_1.xlsx')

KeyboardInterrupt:

In [2]:
df1 = pd.read_excel('./test_data/train_1.xlsx')
df2 = pd.read_excel('./test_data/train_0.xlsx')

In [3]:
df1

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,2.40,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47
0,4,3,4,3,1,2,2,4,4,1,...,4,2,2,4,2,4,1,2,2,4
1,3,2,4,2,4,2,3,4,2,4,...,4,2,2,3,4,3,4,3,4,3
2,2,2,2,1,4,4,4,3,2,2,...,4,2,4,2,4,2,2,4,2,4
3,2,2,1,4,4,1,3,4,2,3,...,1,3,3,4,4,3,4,1,3,3
4,1,3,1,2,3,1,1,2,2,3,...,2,2,4,4,3,2,2,2,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69685,3,1,1,1,4,4,3,3,4,3,...,2,3,4,4,2,1,4,2,3,4
69686,3,1,1,1,4,1,1,2,3,2,...,1,1,2,4,3,4,3,1,1,1
69687,3,1,1,1,2,4,2,3,1,1,...,1,1,2,1,2,3,1,2,1,1
69688,3,1,1,1,2,4,3,3,4,2,...,1,2,1,4,3,1,4,3,4,1
69689,1,4,4,1,4,2,2,3,1,1,...,3,1,3,3,1,1,1,4,2,2

In [11]:
df1['label'] = 1

In [12]:
df1

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47,label
0,4,3,4,3,1,2,2,4,4,1,...,2,2,4,2,4,1,2,2,4,1
1,3,2,4,2,4,2,3,4,2,4,...,2,2,3,4,3,4,3,4,3,1
2,2,2,2,1,4,4,4,3,2,2,...,2,4,2,4,2,2,4,2,4,1
3,2,2,1,4,4,1,3,4,2,3,...,3,3,4,4,3,4,1,3,3,1
4,1,3,1,2,3,1,1,2,2,3,...,2,4,4,3,2,2,2,4,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69685,3,1,1,1,4,4,3,3,4,3,...,3,4,4,2,1,4,2,3,4,1
69686,3,1,1,1,4,1,1,2,3,2,...,1,2,4,3,4,3,1,1,1,1
69687,3,1,1,1,2,4,2,3,1,1,...,1,2,1,2,3,1,2,1,1,1
69688,3,1,1,1,2,4,3,3,4,2,...,2,1,4,3,1,4,3,4,1,1
69689,1,4,4,1,4,2,2,3,1,1,...,1,3,3,1,1,1,4,2,2,1

In [4]:
df2

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,2.40,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47
0,4,3,4,3,1,2,2,4,4,1,...,4,2,2,4,2,4,1,2,2,4
1,3,2,4,2,4,2,3,4,2,4,...,4,2,2,3,4,3,4,3,4,3
2,2,2,2,1,4,4,4,3,2,2,...,4,2,4,2,4,2,2,4,2,4
3,2,2,1,4,4,1,3,4,2,3,...,1,3,3,4,4,3,4,1,3,3
4,1,3,1,2,3,1,1,2,2,3,...,2,2,4,4,3,2,2,2,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11359,4,3,2,1,1,4,2,3,2,4,...,2,3,3,2,2,3,2,3,4,3
11360,4,3,3,4,3,2,4,2,2,4,...,2,3,4,1,3,4,1,4,2,4
11361,4,3,3,4,1,2,2,4,2,2,...,3,2,4,3,1,1,3,3,2,1
11362,4,3,3,2,4,4,4,3,1,2,...,1,1,2,2,2,1,4,1,3,1
11363,4,3,3,1,4,4,1,3,3,3,...,4,2,2,4,4,4,2,1,3,4

In [13]:
df2['label'] = 0
df2

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47,label
0,4,3,4,3,1,2,2,4,4,1,...,2,2,4,2,4,1,2,2,4,0
1,3,2,4,2,4,2,3,4,2,4,...,2,2,3,4,3,4,3,4,3,0
2,2,2,2,1,4,4,4,3,2,2,...,2,4,2,4,2,2,4,2,4,0
3,2,2,1,4,4,1,3,4,2,3,...,3,3,4,4,3,4,1,3,3,0
4,1,3,1,2,3,1,1,2,2,3,...,2,4,4,3,2,2,2,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11359,4,3,2,1,1,4,2,3,2,4,...,3,3,2,2,3,2,3,4,3,0
11360,4,3,3,4,3,2,4,2,2,4,...,3,4,1,3,4,1,4,2,4,0
11361,4,3,3,4,1,2,2,4,2,2,...,2,4,3,1,1,3,3,2,1,0
11362,4,3,3,2,4,4,4,3,1,2,...,1,2,2,2,1,4,1,3,1,0
11363,4,3,3,1,4,4,1,3,3,3,...,2,2,4,4,4,2,1,3,4,0

In [14]:
df = pd.concat([df1, df2], axis=0)

In [15]:
df

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47,label
0,4,3,4,3,1,2,2,4,4,1,...,2,2,4,2,4,1,2,2,4,1
1,3,2,4,2,4,2,3,4,2,4,...,2,2,3,4,3,4,3,4,3,1
2,2,2,2,1,4,4,4,3,2,2,...,2,4,2,4,2,2,4,2,4,1
3,2,2,1,4,4,1,3,4,2,3,...,3,3,4,4,3,4,1,3,3,1
4,1,3,1,2,3,1,1,2,2,3,...,2,4,4,3,2,2,2,4,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11359,4,3,2,1,1,4,2,3,2,4,...,3,3,2,2,3,2,3,4,3,0
11360,4,3,3,4,3,2,4,2,2,4,...,3,4,1,3,4,1,4,2,4,0
11361,4,3,3,4,1,2,2,4,2,2,...,2,4,3,1,1,3,3,2,1,0
11362,4,3,3,2,4,4,4,3,1,2,...,1,2,2,2,1,4,1,3,1,0
11363,4,3,3,1,4,4,1,3,3,3,...,2,2,4,4,4,2,1,3,4,0

In [16]:
df = df.sample(frac=1)

In [17]:
df

,3,2,2.1,3.1,1,4,1.1,2.2,1.2,4.1,...,4.44,3.36,4.45,3.37,3.38,3.39,2.41,4.46,4.47,label
51756,4,1,2,4,3,2,4,1,1,4,...,1,3,2,4,3,4,4,1,2,1
36972,3,2,1,3,1,1,2,4,2,1,...,4,3,1,1,4,1,4,4,1,1
18911,4,1,4,2,4,3,2,1,3,1,...,3,4,2,3,4,2,2,3,4,1
22070,1,4,1,1,4,2,1,3,1,2,...,3,4,2,1,2,4,3,1,3,1
55006,4,1,3,2,3,1,4,4,1,1,...,1,2,2,1,3,1,2,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21694,1,1,4,2,3,1,4,3,2,2,...,2,4,3,4,4,4,1,4,3,1
15144,1,1,3,4,2,4,2,4,1,1,...,3,4,2,1,2,4,2,2,1,1
68631,1,2,3,4,1,4,1,4,3,4,...,1,2,1,2,4,3,1,2,2,1
43809,2,4,1,1,3,1,2,1,4,3,...,2,3,4,1,2,4,3,1,2,1
20500,4,2,1,4,2,4,4,2,2,2,...,2,1,1,1,3,1,2,2,3,1

In [18]:
feature = df.values.tolist()

In [19]:
feature = np.array(feature)

In [20]:
feature.shape

(81054, 153)

In [23]:
feature_1 = feature[:, 0:152]

In [24]:
feature_1.shape

(81054, 152)

In [25]:
feature_2 = feature[:, 152:]

In [26]:
feature_2.shape

(81054, 1)

In [27]:
np.save('feature_new.npy', feature_1)
np.save('label_new.npy', feature_2)

In [28]:
feature_load = np.load('feature_new.npy')
label_load = np.load('label_new.npy')
feature = torch.from_numpy(feature_load).float()
label = torch.from_numpy(label_load).float()

In [29]:
feature.shape

torch.Size([81054, 152])

In [30]:
feature = feature.unsqueeze(1)

In [31]:
feature.shape

torch.Size([81054, 1, 152])

In [32]:
train_dataset = TensorDataset(feature, label)

In [33]:
test1, test2, test3, test4, test5, test6, test7, test8, test9 = torch.utils.data.random_split(train_dataset, [9006, 9006, 9006, 9006, 9006, 9006, 9006, 9006, 9006])

In [34]:
test_loader_1 = DataLoader(test1, batch_size=128, shuffle=True)
test_loader_2 = DataLoader(test2, batch_size=128, shuffle=True)
test_loader_3 = DataLoader(test3, batch_size=128, shuffle=True)
test_loader_4 = DataLoader(test4, batch_size=128, shuffle=True)
test_loader_5 = DataLoader(test5, batch_size=128, shuffle=True)
test_loader_6 = DataLoader(test6, batch_size=128, shuffle=True)
test_loader_7 = DataLoader(test7, batch_size=128, shuffle=True)
test_loader_8 = DataLoader(test8, batch_size=128, shuffle=True)
test_loader_9 = DataLoader(test9, batch_size=128, shuffle=True)

In [38]:
from lib.model.resnet50 import ResNet50
net = ResNet50()
net.load_state_dict(torch.load('resnet50_acc_0.717.pth'))
net.eval()

Sequential(
  (0): Sequential(
    (0): Conv1d(1, 64, kernel_size=(7,), stride=(2,), padding=(3,))
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
  )
  (1): Sequential(
    (0): Residual(
      (conv1): Conv1d(64, 64, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(64, 256, kernel_size=(1,), stride=(1,))
      (conv4): Conv1d(64, 256, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): Residual(
      (conv1): Conv1d(256, 64, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(64, 256, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): Residual(
      (conv1): Conv1d(256, 64, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(64, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(64, 256, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (2): MaxPool1d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (3): Sequential(
    (0): Residual(
      (conv1): Conv1d(256, 128, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(128, 512, kernel_size=(1,), stride=(1,))
      (conv4): Conv1d(256, 512, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): Residual(
      (conv1): Conv1d(512, 128, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(128, 512, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): Residual(
      (conv1): Conv1d(512, 128, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(128, 512, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): Residual(
      (conv1): Conv1d(512, 128, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(128, 512, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (4): MaxPool1d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (5): Sequential(
    (0): Residual(
      (conv1): Conv1d(512, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (conv4): Conv1d(512, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): Residual(
      (conv1): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): Residual(
      (conv1): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): Residual(
      (conv1): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (4): Residual(
      (conv1): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (5): Residual(
      (conv1): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(256, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (6): MaxPool1d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (7): Sequential(
    (0): Residual(
      (conv1): Conv1d(1024, 512, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(512, 2048, kernel_size=(1,), stride=(1,))
      (conv4): Conv1d(1024, 2048, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): Residual(
      (conv1): Conv1d(2048, 512, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(512, 2048, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): Residual(
      (conv1): Conv1d(2048, 512, kernel_size=(1,), stride=(1,))
      (conv2): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv3): Conv1d(512, 2048, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (bn3): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (8): AdaptiveAvgPool1d(output_size=2)
  (9): Flatten(start_dim=1, end_dim=-1)
  (10): Sequential(
    (0): Linear(in_features=4096, out_features=4096, bias=True)
    (1): ReLU()
    (2): BatchNorm1d(4096, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Linear(in_features=4096, out_features=1024, bias=True)
    (4): ReLU()
    (5): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): Linear(in_features=1024, out_features=256, bias=True)
    (7): ReLU()
    (8): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): Linear(in_features=256, out_features=64, bias=True)
    (10): ReLU()
    (11): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): Linear(in_features=64, out_features=1, bias=True)
    (13): Sigmoid()
  )
)

In [40]:
output_list_1 = []
label_list_1 = []

with torch.no_grad():
    for i, (inputs, labels) in enumerate(test_loader_1):
        outputs = np.array(net(inputs))
        output_list_1.extend(outputs)
        label_list_1.extend(labels)

In [41]:
output_list_1 = np.array(output_list_1)
label_list_1 = np.array(label_list_1)

In [42]:
output_list_1.shape

(9006, 1)

In [43]:
label_list_1.shape

(9006, 1)

In [48]:
new = label_list_1.squeeze()
new.shape

(9006,)

In [57]:
new_1 = output_list_1.squeeze()
new_1[7000:8000]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [58]:
new_1.sum()

0.0

In [44]:
output_list_2 = []
label_list_2 = []

with torch.no_grad():
    for i, (inputs, labels) in enumerate(test_loader_2):
        outputs = np.array(net(inputs))
        output_list_2.extend(outputs)
        label_list_2.extend(labels)

In [45]:
output_list_2 = np.array(output_list_2)
label_list_2 = np.array(label_list_2)

In [46]:
my_dict = {}
for i in range(1, 10):
    output_list = []
    label_list = []
    with torch.no_grad():
        for j, (inputs, labels) in enumerate(eval('test_loader_' + str(i))):
            outputs = np.array(net(inputs))
            output_list.extend(outputs)
            label_list.extend(labels)
    output_list = np.array(output_list)
    label_list = np.array(label_list)
    my_dict[f'output_list_{i}'] = output_list.squeeze()
    my_dict[f'label_list_{i}'] = label_list.squeeze()

In [47]:
my_dict

{'output_list_2': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_2': array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [0.],
        [1.]], dtype=float32),
 'output_list_3': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_3': array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [0.],
        [1.]], dtype=float32),
 'output_list_4': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_4': array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [0.]], dtype=float32),
 'output_list_5': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_5': array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 'output_list_6': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_6': array([[1.],
        [0.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 'output_list_7': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_7': array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [1.],
        [1.]], dtype=float32),
 'output_list_8': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_8': array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 'output_list_9': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=float32),
 'label_list_9': array([[1.],
        [1.],
        [1.],
        ...,
        [0.],
        [0.],
        [1.]], dtype=float32)}